### ISSUE TITLE
The "require tfa" permission seems to be a bit confusing

### ISSUE THREAD

**Issue by paraacha** [therealssj/tfa#10]
The TFA module provides a "require tfa" permission but it seems a bit confusing. That's because the permission name suggests that any user without this permission would be able to simply bypass the TFA process during login. But that is not the case as revealed by the module's behavior. 

Therefore, I don't seem to get the rationale behind this permission. Can someone elaborate this?

**Comment by therealssj** [comment]
Yes. I do some places in the TfaLoginForm.php which should have additional hasPermission check for "require tfa" or possibly shift the check to the outermost if statement.

The permission is as it says. Every user who has this permission needs to do tfa

**Comment by paraacha** [comment]
Understood

**Comment by therealssj** [comment]
marked for next commit.
