### ISSUE TITLE
Adherence to Drupal 8 coding standards.

### ISSUE THREAD

**Issue by paraacha** [therealssj/tfa#3]
The Drupal 8 coding standards are missing in a few places in the module. This issue is just a reminder to fix those eventually. 
### In _src/TfaBasePlugin.php_,
- Missing doc comment for getLabel() function.
### In _src/TfaLoginPluginManager.php_,
- Empty doc comment for the class.
### In _src/TfaSendPluginManager.php_,
- Empty doc comment for the class.
### In _src/TfaSetup/TfaTrustedBrowserSetup.php_,
- Missing newline at the end-of-file.
- Multiple blank lines after deleteTrustedBrowsers() function.
- Comment present after a statement in validateSetupForm() function.
### In _src/TfaLogin/TfaTrustedBrowser.php_,
- _use Drupal\tfa\TfaDataTrait;_ is an unused use statement.
### In _src/TfaValidation/TfaHotp.php_,
- Missing space after closing parenthesis in isFallback() function.
### In _src/TfaValidation/TfaTotp.php_,
- _use Drupal\Core\Url;_ is an unused use statement.
### In _tfa.module_,
- In hook implementations, there is no need to document function parameters because they've already been documented in the hook documentation. So,

```
/**
 * Implements hook_user_login()
 *
 * @param $account
 */
```

should be replaced with:

```
/**
 * Implements hook_user_login().
 */
```

and 

```
/**
 * Implements hook_block_access()
 *
 * Remove access to the core user_login_block so we can replace with the TFA login block.
 *
 * @param \Drupal\block\Entity\Block $block
 * @param $operation
 * @param \Drupal\user\Entity\User $account
 *
 * @return \Drupal\Core\Access\AccessResult
 */
```

should be replaced with this also taking care of the 80 chars line limit:

```
/**
 * Implements hook_block_access().
 *
 * Remove access to the core user_login_block so we can replace with the TFA
 * login block.
 */
```
### In _tfa.install_
- Missing description in _@file_ comment.
### In _src/Form/BasicOverview.php_
- Several unused use statements present.
### In _services_tfa/src/Plugin/ServiceDefinition/GenericValidation.php_
- Missing newline at the end-of-file.

**Comment by nerdstein** [comment]
👍
