### ISSUE TITLE
Do not alter user.login route by default

### ISSUE THREAD

**Issue by paraacha** [therealssj/tfa#6]
The TfaRouteSubscriber overrides user.login route with a custom login form. But this replacement should only occur if the Two-Factor Authentication has been enabled from TFA Settings. 

An alternative approach would be to firstly check whether the TFA module has been enabled or not in the TfaLoginForm and then proceed accordingly. 

In any case, currently there is no code present in the module to handle that scenario. Because I've manually tested this and found out that a user is unable to login to a website with TFA module installed but not enabled.

![3](https://cloud.githubusercontent.com/assets/15692050/17290273/1aa90550-57f7-11e6-8956-bafb3d818aed.png)

**Comment by therealssj** [comment]
Aah shit. I changed this part in the last pull only and forgot to check whether plugin is enabled. 
Will fix this soon.

**Comment by nerdstein** [comment]
+1
